/* coding: utf-8 */
/*
Generated by Deepseek
*/
#include<stdio.h>
#include<stdint.h>
#include"madd.h"

void Minimal_Test() {
    Madd_Print(L"Starting minimal test\n");
    
    // 直接测试字符串处理
    Madd_Print(L"Test string 1\n");
    Madd_Print(L"Test string with % special characters\n");
    Madd_Print(L"Element 30 enqueued successfully\n");
    
    // 单独测试队列
    Queue q;
    Queue_Init(&q, 3, sizeof(int));
    
    int data = 10;
    Madd_Print(L"Enqueue 10\n");
    Queue_Enqueue(&q, &data);
    
    data = 20;
    Madd_Print(L"Enqueue 20\n");
    Queue_Enqueue(&q, &data);
    
    data = 30;
    Madd_Print(L"Enqueue 30\n"); // 这里会触发新节点分配
    Queue_Enqueue(&q, &data);
    
    Madd_Print(L"Minimal test completed\n");
}

int main(int argc, char *argv[])
{
	Minimal_Test();
	return 0;
}
