add_executable(test_thread-create thread_base/test/main-create.c)
target_include_directories(test_thread-create PUBLIC thread_base/)
target_link_libraries(test_thread-create PUBLIC madd)
if (${MADD_THREAD_API} STREQUAL "pthread" OR UNIX)
    target_link_libraries(test_thread-create PUBLIC pthread)
endif()
add_test(NAME thread-create COMMAND test_thread-create)

add_executable(test_thread-mutex thread_base/test/main-mutex.c)
target_include_directories(test_thread-mutex PUBLIC thread_base/)
target_link_libraries(test_thread-mutex PUBLIC madd)
if (${MADD_THREAD_API} STREQUAL "pthread" OR UNIX)
    target_link_libraries(test_thread-mutex PUBLIC pthread)
endif()
add_test(NAME thread-mutex COMMAND test_thread-mutex)

add_executable(test_thread-nthread thread_base/test/main-nthread.c)
target_include_directories(test_thread-nthread PUBLIC thread_base/)
target_link_libraries(test_thread-nthread PUBLIC madd)
if (${MADD_THREAD_API} STREQUAL "pthread" OR UNIX)
    target_link_libraries(test_thread-nthread PUBLIC pthread)
endif()
add_test(NAME thread-nthread COMMAND test_thread-nthread)

add_executable(test_thread-condition-variable thread_base/test/main-condition-variable.c)
target_include_directories(test_thread-condition-variable PUBLIC thread_base/)
target_link_libraries(test_thread-condition-variable PUBLIC madd)
if (${MADD_THREAD_API} STREQUAL "pthread" OR UNIX)
    target_link_libraries(test_thread-condition-variable PUBLIC pthread)
endif()
add_test(NAME thread-condition-variable COMMAND test_thread-condition-variable)