site_name: Guide of Math Addition (Madd)
theme: 
  name: readthedocs

nav:
  - Home: intro-home.md
  - Quick Start:
    - Build & Install: intro-build.md
    - Include & Link: intro-include.md
  - Basic Functions:
    - Introduction: basic-intro.md
    - Error & Warning: basic-error-warning.md
    - Binary Number: basic-binary.md
    - Other: basic-other.md