site_name: Guide of Math Addition (Madd)
theme: 
  name: readthedocs

nav:
  - Home: intro-home.md
  - Quick Start:
    - Build & Install: intro-build.md
    - Include & Link: intro-include.md
  - Basic Functions:
    - Introduction: basic-intro.md
    - Error & Warning: basic-error-warning.md
    - Constants: basic-constant.md
    - Binary Number: basic-binary.md
    - Other: basic-other.md
  - Integrate:
    - Introduction: integrate-intro.md
    - Trapezoidal Integral: integrate-trapeze.md
    - Simpson Integral: integrate-Simpson.md
    - Gauss-Legendre Quadrature: integrate-Gauss-Legendre.md
  - Random Number Generator:
    - Instruction: rng-intro.md
  - Sort:
    - Introduction: sort-intro.md
    - Functions: sort-func.md