site_name: Guide of Math Addition (Madd)
theme: 
  name: readthedocs
  custom_dir: docs/overrides

extra_css:
  - css/dark_theme.css

nav:
  - Home:
    - Introduction: intro-home.md
    - Quick Start:
      - Build & Install: intro-build.md
      - Include & Link: intro-include.md
  - Basic Functions:
    - Introduction: basic-intro.md
    - Basic contents:
      - Error & Warning: basic-error-warning.md
      - Constants: basic-constant.md
      - Binary Number: basic-binary.md
    - Complex Number: basic-cnum.md
    - Other: basic-other.md
  - Fast Fourier Transform:
    - Introduction: fft-intro.md
    - FFT Functions: fft-func.md
  - Integrate:
    - Introduction: integrate-intro.md
    - Fundamental Integral:
      - Trapezoidal Integral: integrate-trapeze.md
      - Simpson Integral: integrate-Simpson.md
    - Gauss Quadrature:
      - Gauss-Legendre Quadrature: integrate-Gauss-Legendre.md
  - Random Number Generator:
    - Instruction: rng-intro.md
  - Sort:
    - Introduction: sort-intro.md
    - Functions: sort-func.md
  - Statistics:
    - Introduction: statistics-intro.md
    - Sum, Mean, etc:
      - Kahan Summation: statistics-kahan-sum.md