site_name: Guide of Math Addition (Madd)
theme: 
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - Home: intro-home.md
  - Quick Start:
    - Build & Install: intro-build.md
    - Include & Link: intro-include.md
  - Basic Functions:
    - Introduction: basic-intro.md
    - Error & Warning: basic-error-warning.md
    - Binary Number: basic-binary.md
    - Other: basic-other.md