/* coding: utf-8 */
/*
This code is generated by Deepseek
*/
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdint.h>
#include <stdbool.h>
#include "madd.h"   // Contains Sort_Shell declaration

// Integer comparison function (ascending order)
char int_compare(void* a, void* b, void* other_param) {
    (void)other_param; // Unused parameter
    int ia = *(int*)a;
    int ib = *(int*)b;
    if (ia < ib) return MADD_LESS;
    else if (ia > ib) return MADD_GREATER;
    else return MADD_SAME;
}

// Structure for custom test cases
struct person {
    int id;
    char name[20];
};

// Structure comparison function
char person_compare(void* a, void* b, void* other_param) {
    (void)other_param;
    struct person* pa = (struct person*)a;
    struct person* pb = (struct person*)b;
    if (pa->id < pb->id) return MADD_LESS;
    else if (pa->id > pb->id) return MADD_GREATER;
    else return MADD_SAME;
}

// Print integer array (for debugging)
void print_int_array(const char* label, int* arr, uint64_t n) {
    printf("%s: [", label);
    for (uint64_t i = 0; i < n; i++) {
        printf("%d", arr[i]);
        if (i < n - 1) printf(", ");
    }
    printf("]\n");
}

// Verify array is sorted
bool verify_sorted_int(int* arr, uint64_t n) {
    for (uint64_t i = 0; i < n - 1; i++) {
        if (arr[i] > arr[i + 1]) {
            return false;
        }
    }
    return true;
}

// Verify structure array is sorted
bool verify_sorted_person(struct person* arr, uint64_t n) {
    for (uint64_t i = 0; i < n - 1; i++) {
        if (arr[i].id > arr[i + 1].id) {
            return false;
        }
    }
    return true;
}

// Test cases
void test_empty() {
    int empty_arr[1] = {0};
    Sort_Shell(0, sizeof(int), empty_arr, int_compare, NULL);
    printf("Test Empty: PASSED\n");
}

void test_single() {
    int single_arr[1] = {42};
    Sort_Shell(1, sizeof(int), single_arr, int_compare, NULL);
    printf("Test Single Element: PASSED\n");
}

void test_sorted() {
    int arr[5] = {1, 2, 3, 4, 5};
    Sort_Shell(5, sizeof(int), arr, int_compare, NULL);
    
    if (verify_sorted_int(arr, 5)) {
        printf("Test Sorted Array: PASSED\n");
    } else {
        print_int_array("Test Sorted Array FAILED", arr, 5);
    }
}

void test_reverse() {
    int arr[5] = {9, 7, 5, 3, 1};
    Sort_Shell(5, sizeof(int), arr, int_compare, NULL);
    
    if (verify_sorted_int(arr, 5)) {
        printf("Test Reverse Order: PASSED\n");
    } else {
        print_int_array("Test Reverse Order FAILED", arr, 5);
    }
}

void test_duplicates() {
    int arr[7] = {3, 1, 4, 1, 5, 9, 2};
    Sort_Shell(7, sizeof(int), arr, int_compare, NULL);
    
    if (verify_sorted_int(arr, 7)) {
        printf("Test Duplicates: PASSED\n");
    } else {
        print_int_array("Test Duplicates FAILED", arr, 7);
    }
}

void test_random_large() {
    const uint64_t size = 1000;
    int* arr = malloc(size * sizeof(int));
    if (!arr) {
        printf("Memory allocation failed for large test\n");
        return;
    }
    
    srand(time(NULL));
    for (uint64_t i = 0; i < size; i++) {
        arr[i] = rand() % 1000;
    }
    
    Sort_Shell(size, sizeof(int), arr, int_compare, NULL);
    
    if (verify_sorted_int(arr, size)) {
        printf("Test Large Random Array (1000 elements): PASSED\n");
    } else {
        // Print first and last 5 elements for debugging
        printf("Test Large Random Array FAILED. Sample: [");
        for (int i = 0; i < 5; i++) printf("%d ", arr[i]);
        printf("... ");
        for (int i = size - 5; i < size; i++) printf("%d ", arr[i]);
        printf("]\n");
    }
    
    free(arr);
}

void test_structures() {
    struct person people[4] = {
        {102, "Alice"},
        {101, "Bob"},
        {104, "Charlie"},
        {103, "Diana"}
    };
    
    Sort_Shell(4, sizeof(struct person), people, person_compare, NULL);
    
    if (verify_sorted_person(people, 4)) {
        printf("Test Structure Sorting: PASSED\n");
    } else {
        printf("Test Structure Sorting FAILED. Results:\n");
        for (int i = 0; i < 4; i++) {
            printf("  ID: %d, Name: %s\n", people[i].id, people[i].name);
        }
    }
}

void test_edge_cases() {
    // All elements same
    int same[5] = {7, 7, 7, 7, 7};
    Sort_Shell(5, sizeof(int), same, int_compare, NULL);
    
    // Two elements
    int two[2] = {10, 5};
    Sort_Shell(2, sizeof(int), two, int_compare, NULL);
    
    if (verify_sorted_int(same, 5) && verify_sorted_int(two, 2)) {
        printf("Test Edge Cases: PASSED\n");
    } else {
        printf("Test Edge Cases FAILED\n");
        print_int_array("Same elements", same, 5);
        print_int_array("Two elements", two, 2);
    }
}

int main() {
    printf("===== Starting Shell Sort Tests =====\n");
    
    test_empty();
    test_single();
    test_sorted();
    test_reverse();
    test_duplicates();
    test_edge_cases();
    test_random_large();
    test_structures();
    
    printf("===== All Tests Completed =====\n");
    return 0;
}