/* coding: utf-8 */
/*
Generated by Deepseek
*/
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include "madd.h"

bool flag_enable_multithread = false;

// 测试大于1024字节的元素
typedef struct {
    double data[200]; // 1600 bytes
    char id[50];
} LargeStruct;

// 测试比较函数
bool int_compare(void *a, void *b, void *other_param) {
    (void)other_param;
    return *(int*)a <= *(int*)b;
}

bool float_compare(void *a, void *b, void *other_param) {
    (void)other_param;
    return *(float*)a <= *(float*)b;
}

// 结构体测试
typedef struct {
    int id;
    char name[20];
    float score;
} Student;

bool student_compare(void *a, void *b, void *other_param) {
    (void)other_param;
    return ((Student*)a)->score <= ((Student*)b)->score;
}

// 辅助函数：验证数组是否已排序
bool verify_sorted(void *arr, uint64_t n, size_t size, 
                  bool (*cmp)(void*, void*, void*), void *param) {
    for (uint64_t i = 1; i < n; i++) {
        void *prev = (char*)arr + (i-1)*size;
        void *curr = (char*)arr + i*size;
        if (!cmp(prev, curr, param)) {
            printf("Validation failed at position %lu\n", i);
            return false;
        }
    }
    return true;
}

// 打印整数数组
void print_int_array(int arr[], uint64_t n) {
    for (uint64_t i = 0; i < n; i++) {
        printf("%d ", arr[i]);
    }
    printf("\n");
}

// 1. 基础测试：小规模整数数组
void test_basic_integer() {
    printf("Running test_basic_integer...\n");
    int arr[] = {5, 2, 9, 1, 5, 6};
    uint64_t n = sizeof(arr)/sizeof(arr[0]);
    
    printf("Original array: ");
    print_int_array(arr, n);
    
    Sort_Quicksort(n, sizeof(int), arr, int_compare, NULL);
    
    printf("Sorted array:   ");
    print_int_array(arr, n);
    
    if (verify_sorted(arr, n, sizeof(int), int_compare, NULL)) {
        printf("Test PASSED\n\n");
    } else {
        printf("Test FAILED\n\n");
    }
}

// 2. 边界测试
void test_edge_cases() {
    printf("Running test_edge_cases...\n");
    
    // 空数组
    int *empty = NULL;
    Sort_Quicksort(0, sizeof(int), empty, int_compare, NULL);
    printf("Empty array test completed\n");
    
    // 单元素数组
    int single = 42;
    Sort_Quicksort(1, sizeof(int), &single, int_compare, NULL);
    printf("Single element test completed\n");
    
    // 已排序数组
    int sorted[] = {1, 2, 3, 4, 5};
    uint64_t n_sorted = sizeof(sorted)/sizeof(sorted[0]);
    Sort_Quicksort(n_sorted, sizeof(int), sorted, int_compare, NULL);
    if (verify_sorted(sorted, n_sorted, sizeof(int), int_compare, NULL)) {
        printf("Sorted array test PASSED\n");
    }
    
    // 逆序数组
    int reversed[] = {9, 8, 7, 6, 5, 4, 3, 2, 1};
    uint64_t n_reversed = sizeof(reversed)/sizeof(reversed[0]);
    Sort_Quicksort(n_reversed, sizeof(int), reversed, int_compare, NULL);
    if (verify_sorted(reversed, n_reversed, sizeof(int), int_compare, NULL)) {
        printf("Reversed array test PASSED\n");
    }
    
    // 全相同元素
    int same[] = {5, 5, 5, 5, 5};
    uint64_t n_same = sizeof(same)/sizeof(same[0]);
    Sort_Quicksort(n_same, sizeof(int), same, int_compare, NULL);
    if (verify_sorted(same, n_same, sizeof(int), int_compare, NULL)) {
        printf("Same elements test PASSED\n\n");
    }
}

// 3. 浮点数测试
void test_floats() {
    printf("Running test_floats...\n");
    float arr[] = {3.14f, 2.71f, 1.41f, 1.62f, 0.99f, 9.81f};
    uint64_t n = sizeof(arr)/sizeof(arr[0]);
    
    printf("Original floats: ");
    for (uint64_t i = 0; i < n; i++) printf("%.2f ", arr[i]);
    printf("\n");
    
    Sort_Quicksort(n, sizeof(float), arr, float_compare, NULL);
    
    printf("Sorted floats:   ");
    for (uint64_t i = 0; i < n; i++) printf("%.2f ", arr[i]);
    printf("\n");
    
    if (verify_sorted(arr, n, sizeof(float), float_compare, NULL)) {
        printf("Test PASSED\n\n");
    } else {
        printf("Test FAILED\n\n");
    }
}

// 4. 结构体测试
void test_structs() {
    printf("Running test_structs...\n");
    Student students[] = {
        {1, "Alice", 88.5f},
        {2, "Bob", 92.3f},
        {3, "Charlie", 75.0f},
        {4, "David", 95.0f},
        {5, "Eva", 81.2f}
    };
    uint64_t n = sizeof(students)/sizeof(students[0]);
    
    printf("Original students:\n");
    for (uint64_t i = 0; i < n; i++) {
        printf("  %s: %.1f\n", students[i].name, students[i].score);
    }
    
    Sort_Quicksort(n, sizeof(Student), students, student_compare, NULL);
    
    printf("\nSorted by score:\n");
    for (uint64_t i = 0; i < n; i++) {
        printf("  %s: %.1f\n", students[i].name, students[i].score);
    }
    
    if (verify_sorted(students, n, sizeof(Student), student_compare, NULL)) {
        printf("Test PASSED\n\n");
    } else {
        printf("Test FAILED\n\n");
    }
}

// 5. 大规模性能测试
void test_performance() {
    printf("Running test_performance...\n");
    const uint64_t large_size = 1000000;
    int *large_arr = malloc(large_size * sizeof(int));
    if (!large_arr) {
        perror("Memory allocation failed");
        return;
    }
    
    // 生成随机数据
    srand(time(NULL));
    for (uint64_t i = 0; i < large_size; i++) {
        large_arr[i] = rand() % 1000000;
    }
    
    clock_t start = clock();
    Sort_Quicksort(large_size, sizeof(int), large_arr, int_compare, NULL);
    clock_t end = clock();
    
    double time_taken = ((double)(end - start)) / CLOCKS_PER_SEC;
    printf("Sorted %lu elements in %.3f seconds\n", large_size, time_taken);
    
    if (verify_sorted(large_arr, large_size, sizeof(int), int_compare, NULL)) {
        printf("Validation PASSED\n");
    } else {
        printf("Validation FAILED\n");
    }
    
    // 测试已排序数组的性能
    start = clock();
    Sort_Quicksort(large_size, sizeof(int), large_arr, int_compare, NULL);
    end = clock();
    printf("Sorted already-sorted array in %.3f seconds\n", 
          ((double)(end - start)) / CLOCKS_PER_SEC);
    
    // 测试逆序数组的性能
    for (uint64_t i = 0; i < large_size/2; i++) {
        int temp = large_arr[i];
        large_arr[i] = large_arr[large_size-1-i];
        large_arr[large_size-1-i] = temp;
    }
    
    start = clock();
    Sort_Quicksort(large_size, sizeof(int), large_arr, int_compare, NULL);
    end = clock();
    printf("Sorted reversed array in %.3f seconds\n", 
          ((double)(end - start)) / CLOCKS_PER_SEC);
    
    free(large_arr);
    printf("Test completed\n\n");
}

// 比较函数
bool large_compare(void *a, void *b, void *param) {
    (void)param;
    double sum_a = 0, sum_b = 0;
    for (int i = 0; i < 200; i++) {
        sum_a += ((LargeStruct*)a)->data[i];
        sum_b += ((LargeStruct*)b)->data[i];
    }
    return sum_a <= sum_b;
}

// 6. 内存测试（大元素大小）
void test_large_elements() {
    printf("Running test_large_elements...\n");
    
    const int n = 10;
    LargeStruct arr[10 /* n */];
    
    // 初始化
    srand(time(NULL));
    for (int i = 0; i < n; i++) {
        for (int j = 0; j < 200; j++) {
            arr[i].data[j] = (double)rand() / RAND_MAX;
        }
        snprintf(arr[i].id, sizeof(arr[i].id), "ID-%03d", i);
    }
    
    Sort_Quicksort(n, sizeof(LargeStruct), arr, large_compare, NULL);
    
    // 验证
    bool valid = true;
    for (int i = 1; i < n; i++) {
        double sum_prev = 0, sum_curr = 0;
        for (int j = 0; j < 200; j++) {
            sum_prev += arr[i-1].data[j];
            sum_curr += arr[i].data[j];
        }
        if (sum_prev > sum_curr) {
            printf("Validation failed at position %d\n", i);
            valid = false;
            break;
        }
    }
    
    if (valid) {
        printf("Test PASSED\n\n");
    } else {
        printf("Test FAILED\n\n");
    }
}

int main(int argc, char *argv[]) {
    madd_error_keep_print = true;
    if (argc > 1){
        int arg1 = atoi(argv[1]);
        flag_enable_multithread = (arg1 != 0);
    }
    wchar_t multithread_info[30];
    swprintf(multithread_info, 30, L"multithread enabled: %d\n", flag_enable_multithread);
    //Madd_Print(multithread_info);
    //printf("multithread enabled:\t%d\n", flag_enable_multithread);

    test_basic_integer();
    test_edge_cases();
    test_floats();
    test_structs();
    test_large_elements();
    test_performance();
    
    printf("All tests completed.\n");
    return 0;
}